package POJO_entities;
// Generated May 22, 2016 3:15:16 PM by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InvStockcard generated by hbm2java
 */
@Entity
@Table(name = "inv_stockcard", catalog = "qlquanan")
public class InvStockcard implements java.io.Serializable {

	private Long id;
	private BaseProduct baseProduct;
	private String action;
	private String referenceCode;
	private BigDecimal qtyTransacted;
	private BigDecimal qtyAvailable;
	private BigDecimal cogs;
	private String comment;
	private int createdUser;
	private Date createdDate;
	private Date updatedDate;
	private Integer updatedUser;
	private boolean isDeleted;
	private String deletedNote;
	private Date deletedDate;
	private Integer deletedUser;
	private int companyId;
	private BigDecimal price;
	private BigDecimal unitPrice;
	private BigDecimal priceWithFee;

	public InvStockcard() {
	}

	public InvStockcard(BaseProduct baseProduct, String action, String referenceCode, BigDecimal qtyTransacted,
			BigDecimal qtyAvailable, BigDecimal cogs, int createdUser, boolean isDeleted, int companyId,
			BigDecimal price, BigDecimal unitPrice, BigDecimal priceWithFee) {
		this.baseProduct = baseProduct;
		this.action = action;
		this.referenceCode = referenceCode;
		this.qtyTransacted = qtyTransacted;
		this.qtyAvailable = qtyAvailable;
		this.cogs = cogs;
		this.createdUser = createdUser;
		this.isDeleted = isDeleted;
		this.companyId = companyId;
		this.price = price;
		this.unitPrice = unitPrice;
		this.priceWithFee = priceWithFee;
	}

	public InvStockcard(BaseProduct baseProduct, String action, String referenceCode, BigDecimal qtyTransacted,
			BigDecimal qtyAvailable, BigDecimal cogs, String comment, int createdUser, Date createdDate,
			Date updatedDate, Integer updatedUser, boolean isDeleted, String deletedNote, Date deletedDate,
			Integer deletedUser, int companyId, BigDecimal price, BigDecimal unitPrice, BigDecimal priceWithFee) {
		this.baseProduct = baseProduct;
		this.action = action;
		this.referenceCode = referenceCode;
		this.qtyTransacted = qtyTransacted;
		this.qtyAvailable = qtyAvailable;
		this.cogs = cogs;
		this.comment = comment;
		this.createdUser = createdUser;
		this.createdDate = createdDate;
		this.updatedDate = updatedDate;
		this.updatedUser = updatedUser;
		this.isDeleted = isDeleted;
		this.deletedNote = deletedNote;
		this.deletedDate = deletedDate;
		this.deletedUser = deletedUser;
		this.companyId = companyId;
		this.price = price;
		this.unitPrice = unitPrice;
		this.priceWithFee = priceWithFee;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ProductItemID", nullable = false)
	public BaseProduct getBaseProduct() {
		return this.baseProduct;
	}

	public void setBaseProduct(BaseProduct baseProduct) {
		this.baseProduct = baseProduct;
	}

	@Column(name = "Action", nullable = false)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	@Column(name = "ReferenceCode", nullable = false, length = 20)
	public String getReferenceCode() {
		return this.referenceCode;
	}

	public void setReferenceCode(String referenceCode) {
		this.referenceCode = referenceCode;
	}

	@Column(name = "QtyTransacted", nullable = false, precision = 20, scale = 4)
	public BigDecimal getQtyTransacted() {
		return this.qtyTransacted;
	}

	public void setQtyTransacted(BigDecimal qtyTransacted) {
		this.qtyTransacted = qtyTransacted;
	}

	@Column(name = "QtyAvailable", nullable = false, precision = 20, scale = 4)
	public BigDecimal getQtyAvailable() {
		return this.qtyAvailable;
	}

	public void setQtyAvailable(BigDecimal qtyAvailable) {
		this.qtyAvailable = qtyAvailable;
	}

	@Column(name = "COGS", nullable = false, scale = 4)
	public BigDecimal getCogs() {
		return this.cogs;
	}

	public void setCogs(BigDecimal cogs) {
		this.cogs = cogs;
	}

	@Column(name = "Comment", length = 500)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "CreatedUser", nullable = false)
	public int getCreatedUser() {
		return this.createdUser;
	}

	public void setCreatedUser(int createdUser) {
		this.createdUser = createdUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedDate", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "UpdatedUser")
	public Integer getUpdatedUser() {
		return this.updatedUser;
	}

	public void setUpdatedUser(Integer updatedUser) {
		this.updatedUser = updatedUser;
	}

	@Column(name = "IsDeleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "DeletedNote", length = 200)
	public String getDeletedNote() {
		return this.deletedNote;
	}

	public void setDeletedNote(String deletedNote) {
		this.deletedNote = deletedNote;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DeletedDate", length = 19)
	public Date getDeletedDate() {
		return this.deletedDate;
	}

	public void setDeletedDate(Date deletedDate) {
		this.deletedDate = deletedDate;
	}

	@Column(name = "DeletedUser")
	public Integer getDeletedUser() {
		return this.deletedUser;
	}

	public void setDeletedUser(Integer deletedUser) {
		this.deletedUser = deletedUser;
	}

	@Column(name = "CompanyID", nullable = false)
	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	@Column(name = "Price", nullable = false, scale = 4)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "UnitPrice", nullable = false, scale = 4)
	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "PriceWithFee", nullable = false, scale = 4)
	public BigDecimal getPriceWithFee() {
		return this.priceWithFee;
	}

	public void setPriceWithFee(BigDecimal priceWithFee) {
		this.priceWithFee = priceWithFee;
	}

}
