package POJO_entities;
// Generated May 22, 2016 3:15:16 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SoSaleorderReceiptvoucher generated by hbm2java
 */
@Entity
@Table(name = "so_saleorder_receiptvoucher", catalog = "qlquanan")
public class SoSaleorderReceiptvoucher implements java.io.Serializable {

	private Long id;
	private SoReceiptvoucher soReceiptvoucher;
	private SoSaleorder soSaleorder;
	private String saleOrderCode;
	private String receiptVoucherCode;
	private Date createdDate;
	private int createdUser;
	private Date updatedDate;
	private Integer updatedUser;
	private boolean isDeleted;
	private String deletedNote;
	private Date deletedDate;
	private Integer deletedUser;
	private int companyId;

	public SoSaleorderReceiptvoucher() {
	}

	public SoSaleorderReceiptvoucher(SoReceiptvoucher soReceiptvoucher, SoSaleorder soSaleorder, String saleOrderCode,
			String receiptVoucherCode, Date createdDate, int createdUser, boolean isDeleted, int companyId) {
		this.soReceiptvoucher = soReceiptvoucher;
		this.soSaleorder = soSaleorder;
		this.saleOrderCode = saleOrderCode;
		this.receiptVoucherCode = receiptVoucherCode;
		this.createdDate = createdDate;
		this.createdUser = createdUser;
		this.isDeleted = isDeleted;
		this.companyId = companyId;
	}

	public SoSaleorderReceiptvoucher(SoReceiptvoucher soReceiptvoucher, SoSaleorder soSaleorder, String saleOrderCode,
			String receiptVoucherCode, Date createdDate, int createdUser, Date updatedDate, Integer updatedUser,
			boolean isDeleted, String deletedNote, Date deletedDate, Integer deletedUser, int companyId) {
		this.soReceiptvoucher = soReceiptvoucher;
		this.soSaleorder = soSaleorder;
		this.saleOrderCode = saleOrderCode;
		this.receiptVoucherCode = receiptVoucherCode;
		this.createdDate = createdDate;
		this.createdUser = createdUser;
		this.updatedDate = updatedDate;
		this.updatedUser = updatedUser;
		this.isDeleted = isDeleted;
		this.deletedNote = deletedNote;
		this.deletedDate = deletedDate;
		this.deletedUser = deletedUser;
		this.companyId = companyId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ReceiptVoucherID", nullable = false)
	public SoReceiptvoucher getSoReceiptvoucher() {
		return this.soReceiptvoucher;
	}

	public void setSoReceiptvoucher(SoReceiptvoucher soReceiptvoucher) {
		this.soReceiptvoucher = soReceiptvoucher;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SaleOrderID", nullable = false)
	public SoSaleorder getSoSaleorder() {
		return this.soSaleorder;
	}

	public void setSoSaleorder(SoSaleorder soSaleorder) {
		this.soSaleorder = soSaleorder;
	}

	@Column(name = "SaleOrderCode", nullable = false, length = 20)
	public String getSaleOrderCode() {
		return this.saleOrderCode;
	}

	public void setSaleOrderCode(String saleOrderCode) {
		this.saleOrderCode = saleOrderCode;
	}

	@Column(name = "ReceiptVoucherCode", nullable = false, length = 20)
	public String getReceiptVoucherCode() {
		return this.receiptVoucherCode;
	}

	public void setReceiptVoucherCode(String receiptVoucherCode) {
		this.receiptVoucherCode = receiptVoucherCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CreatedUser", nullable = false)
	public int getCreatedUser() {
		return this.createdUser;
	}

	public void setCreatedUser(int createdUser) {
		this.createdUser = createdUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedDate", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "UpdatedUser")
	public Integer getUpdatedUser() {
		return this.updatedUser;
	}

	public void setUpdatedUser(Integer updatedUser) {
		this.updatedUser = updatedUser;
	}

	@Column(name = "IsDeleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "DeletedNote", length = 200)
	public String getDeletedNote() {
		return this.deletedNote;
	}

	public void setDeletedNote(String deletedNote) {
		this.deletedNote = deletedNote;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DeletedDate", length = 19)
	public Date getDeletedDate() {
		return this.deletedDate;
	}

	public void setDeletedDate(Date deletedDate) {
		this.deletedDate = deletedDate;
	}

	@Column(name = "DeletedUser")
	public Integer getDeletedUser() {
		return this.deletedUser;
	}

	public void setDeletedUser(Integer deletedUser) {
		this.deletedUser = deletedUser;
	}

	@Column(name = "CompanyID", nullable = false)
	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

}
