package POJO_entities;
// Generated May 22, 2016 3:15:16 PM by Hibernate Tools 4.0.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SystemRolelist generated by hbm2java
 */
@Entity
@Table(name = "system_rolelist", catalog = "qlquanan")
public class SystemRolelist implements java.io.Serializable {

	private Long id;
	private String key;
	private String value;
	private boolean isDeleted;
	private Set<SystemGroupRolelist> systemGroupRolelists = new HashSet<SystemGroupRolelist>(0);

	public SystemRolelist() {
	}

	public SystemRolelist(String key, String value, boolean isDeleted) {
		this.key = key;
		this.value = value;
		this.isDeleted = isDeleted;
	}

	public SystemRolelist(String key, String value, boolean isDeleted, Set<SystemGroupRolelist> systemGroupRolelists) {
		this.key = key;
		this.value = value;
		this.isDeleted = isDeleted;
		this.systemGroupRolelists = systemGroupRolelists;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "Key", nullable = false, length = 511)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "Value", nullable = false)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "IsDeleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "systemRolelist")
	public Set<SystemGroupRolelist> getSystemGroupRolelists() {
		return this.systemGroupRolelists;
	}

	public void setSystemGroupRolelists(Set<SystemGroupRolelist> systemGroupRolelists) {
		this.systemGroupRolelists = systemGroupRolelists;
	}

}
