package POJO_entities;
// Generated May 22, 2016 3:15:16 PM by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SystemUserAccount generated by hbm2java
 */
@Entity
@Table(name = "system_user_account", catalog = "qlquanan")
public class SystemUserAccount implements java.io.Serializable {

	private long id;
	private String username;
	private String password;
	private long groupId;
	private boolean isDeleted;
	private boolean isActived;
	private Date createdDate;
	private int createdUser;
	private Date updatedDate;
	private Integer updatedUser;
	private Date deletedDate;
	private Integer deletedUser;
	private Set<SystemUser> systemUsers = new HashSet<SystemUser>(0);

	public SystemUserAccount() {
	}

	public SystemUserAccount(long id, String username, String password, long groupId, boolean isDeleted,
			boolean isActived, Date createdDate, int createdUser) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.groupId = groupId;
		this.isDeleted = isDeleted;
		this.isActived = isActived;
		this.createdDate = createdDate;
		this.createdUser = createdUser;
	}

	public SystemUserAccount(long id, String username, String password, long groupId, boolean isDeleted,
			boolean isActived, Date createdDate, int createdUser, Date updatedDate, Integer updatedUser,
			Date deletedDate, Integer deletedUser, Set<SystemUser> systemUsers) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.groupId = groupId;
		this.isDeleted = isDeleted;
		this.isActived = isActived;
		this.createdDate = createdDate;
		this.createdUser = createdUser;
		this.updatedDate = updatedDate;
		this.updatedUser = updatedUser;
		this.deletedDate = deletedDate;
		this.deletedUser = deletedUser;
		this.systemUsers = systemUsers;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "Username", nullable = false, length = 100)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "Password", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "GroupId", nullable = false)
	public long getGroupId() {
		return this.groupId;
	}

	public void setGroupId(long groupId) {
		this.groupId = groupId;
	}

	@Column(name = "IsDeleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "IsActived", nullable = false)
	public boolean isIsActived() {
		return this.isActived;
	}

	public void setIsActived(boolean isActived) {
		this.isActived = isActived;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDate", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "CreatedUser", nullable = false)
	public int getCreatedUser() {
		return this.createdUser;
	}

	public void setCreatedUser(int createdUser) {
		this.createdUser = createdUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedDate", length = 19)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "UpdatedUser")
	public Integer getUpdatedUser() {
		return this.updatedUser;
	}

	public void setUpdatedUser(Integer updatedUser) {
		this.updatedUser = updatedUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DeletedDate", length = 19)
	public Date getDeletedDate() {
		return this.deletedDate;
	}

	public void setDeletedDate(Date deletedDate) {
		this.deletedDate = deletedDate;
	}

	@Column(name = "DeletedUser")
	public Integer getDeletedUser() {
		return this.deletedUser;
	}

	public void setDeletedUser(Integer deletedUser) {
		this.deletedUser = deletedUser;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "systemUserAccount")
	public Set<SystemUser> getSystemUsers() {
		return this.systemUsers;
	}

	public void setSystemUsers(Set<SystemUser> systemUsers) {
		this.systemUsers = systemUsers;
	}

}
