package POJO_entities;
// Generated May 22, 2016 3:15:16 PM by Hibernate Tools 4.0.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SystemGroup generated by hbm2java
 */
@Entity
@Table(name = "system_group", catalog = "qlquanan")
public class SystemGroup implements java.io.Serializable {

	private Long id;
	private String groupName;
	private String description;
	private boolean isDeleted;
	private Set<SystemGroupRolelist> systemGroupRolelists = new HashSet<SystemGroupRolelist>(0);

	public SystemGroup() {
	}

	public SystemGroup(String groupName, boolean isDeleted) {
		this.groupName = groupName;
		this.isDeleted = isDeleted;
	}

	public SystemGroup(String groupName, String description, boolean isDeleted,
			Set<SystemGroupRolelist> systemGroupRolelists) {
		this.groupName = groupName;
		this.description = description;
		this.isDeleted = isDeleted;
		this.systemGroupRolelists = systemGroupRolelists;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "GroupName", nullable = false, length = 511)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@Column(name = "Description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "IsDeleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "systemGroup")
	public Set<SystemGroupRolelist> getSystemGroupRolelists() {
		return this.systemGroupRolelists;
	}

	public void setSystemGroupRolelists(Set<SystemGroupRolelist> systemGroupRolelists) {
		this.systemGroupRolelists = systemGroupRolelists;
	}

}
