package POJO_entities;
// Generated May 22, 2016 3:15:16 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SystemSalary generated by hbm2java
 */
@Entity
@Table(name = "system_salary", catalog = "qlquanan")
public class SystemSalary implements java.io.Serializable {

	private long id;
	private SchWorkshift schWorkshift;
	private long basicSalary;
	private boolean isDeleted;

	public SystemSalary() {
	}

	public SystemSalary(long id, SchWorkshift schWorkshift, long basicSalary, boolean isDeleted) {
		this.id = id;
		this.schWorkshift = schWorkshift;
		this.basicSalary = basicSalary;
		this.isDeleted = isDeleted;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "WorkShiftId", nullable = false)
	public SchWorkshift getSchWorkshift() {
		return this.schWorkshift;
	}

	public void setSchWorkshift(SchWorkshift schWorkshift) {
		this.schWorkshift = schWorkshift;
	}

	@Column(name = "BasicSalary", nullable = false)
	public long getBasicSalary() {
		return this.basicSalary;
	}

	public void setBasicSalary(long basicSalary) {
		this.basicSalary = basicSalary;
	}

	@Column(name = "IsDeleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

}
