package POJO_entities;
// Generated May 22, 2016 3:15:16 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblTables generated by hbm2java
 */
@Entity
@Table(name = "tbl_tables", catalog = "qlquanan")
public class TblTables implements java.io.Serializable {

	private long id;
	private String name;
	private String description;
	private short status;
	private short maxCustomer;
	private boolean isDeleted;

	public TblTables() {
	}

	public TblTables(long id, String name, short status, short maxCustomer, boolean isDeleted) {
		this.id = id;
		this.name = name;
		this.status = status;
		this.maxCustomer = maxCustomer;
		this.isDeleted = isDeleted;
	}

	public TblTables(long id, String name, String description, short status, short maxCustomer, boolean isDeleted) {
		this.id = id;
		this.name = name;
		this.description = description;
		this.status = status;
		this.maxCustomer = maxCustomer;
		this.isDeleted = isDeleted;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "Status", nullable = false)
	public short getStatus() {
		return this.status;
	}

	public void setStatus(short status) {
		this.status = status;
	}

	@Column(name = "MaxCustomer", nullable = false)
	public short getMaxCustomer() {
		return this.maxCustomer;
	}

	public void setMaxCustomer(short maxCustomer) {
		this.maxCustomer = maxCustomer;
	}

	@Column(name = "IsDeleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

}
