package POJO_entities;
// Generated May 22, 2016 3:15:16 PM by Hibernate Tools 4.0.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TblUserTool generated by hbm2java
 */
@Entity
@Table(name = "tbl_user_tool", catalog = "qlquanan")
public class TblUserTool implements java.io.Serializable {

	private long id;
	private SystemUser systemUser;
	private String toolName;
	private boolean isDeleted;

	public TblUserTool() {
	}

	public TblUserTool(long id, SystemUser systemUser, String toolName, boolean isDeleted) {
		this.id = id;
		this.systemUser = systemUser;
		this.toolName = toolName;
		this.isDeleted = isDeleted;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserId", nullable = false)
	public SystemUser getSystemUser() {
		return this.systemUser;
	}

	public void setSystemUser(SystemUser systemUser) {
		this.systemUser = systemUser;
	}

	@Column(name = "ToolName", nullable = false, length = 1000)
	public String getToolName() {
		return this.toolName;
	}

	public void setToolName(String toolName) {
		this.toolName = toolName;
	}

	@Column(name = "IsDeleted", nullable = false)
	public boolean isIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

}
